apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: dynatrace-lab
  labels:
    app: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka
        image: chandu4440/discovery-server:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 8761
        env:
        - name: ERROR_RATE
          value: "0.15"
        - name: MIN_LATENCY_MS
          value: "10"
        - name: MAX_LATENCY_MS
          value: "800"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
