apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  namespace: dynatrace-lab
  labels:
    app: todo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
      - name: catalog
        image: chandu4440/catalog-service:v4
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        env:
        - name: FRAUD_BASE_URL
          value: http://todo-server-discovery:8761
        - name: JAVA_TOOL_OPTIONS
          value: "-Xms64m -Xmx128m"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
