apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  namespace: dynatrace-lab
  labels:
    app: catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - name: catalog
        image: chandu4440/catalog-service:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        env:
        - name: FRAUD_BASE_URL
          value: http://eureka-server:8761
        - name: JAVA_TOOL_OPTIONS
          value: "-Xms64m -Xmx128m"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
