apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-website
  namespace: dynatrace-lab
  labels:
    app: website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: chandu4440/main-website:v4
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        - name: ORDERS_BASE_URL
          value: http://catalog-service
        - name: JAVA_TOOL_OPTIONS
          value: "-Xms64m -Xmx128m"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
